mysql:
 username: root
 password: Tjj@2002
 host: 123.56.9.154
 port: 3306
 dbname: IM
 timeout: 10s
redis:
 addr: "123.56.9.154:6379"
 password: "Tjj@2002"
 poolSize: 30
 DB: 0
 minIdleConn: 30